{% set name = "hydrotrend" %}
{% set version = "3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms-contrib/{{ name }}
  git_branch: master

requirements:
  build:
    - cmake
    - gcc # [not win]
  run:
    - libgcc

test:
  commands:
    - hydrotrend -h
    - curl https://raw.githubusercontent.com/csdms-contrib/hydrotrend/master/data/input/HYDRO.IN > ./HYDRO.IN
    - curl https://raw.githubusercontent.com/csdms-contrib/hydrotrend/master/data/input/HYDRO0.HYPS > ./HYDRO0.HYPS
    - hydrotrend --prefix=HYDRO --in-dir=. --out-dir=.

build:
  number: 3

about:
  home: http://csdms.colorado.edu/wiki/Model:HydroTrend
  license: MIT
  summary: Climate driven hydrological transport model
  description:
    HydroTrend v3.0 is a climate-driven hydrological water balance
    and transport model that simulates water discharge and sediment
    load at a river outlet.
  doc_url: http://csdms.colorado.edu/wiki/Model:HydroTrend
  dev_url: http://github.com/csdms-contrib/hydrotrend
