{% set name = "hydrotrend" %}
{% set version = "3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/mcflugen/{{ name }}
  git_branch: add-bmi-metadata

requirements:
  build:
    - cmake
    - gcc
  run:
    - libgcc

test:
  commands:
    - hydrotrend -h

build:
  number: 0
