{% set name = "hydrotrend" %}
{% set version = "3.0" %}
{% set build_string = environ.get('GIT_BUILD_STR', '') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/mcflugen/{{ name }}
  git_branch: add-bmi-metadata

requirements:
  build:
    - cmake
    - gcc # [not win]
  run:
    - libgcc

test:
  commands:
    - hydrotrend -h
    - mkdir input output
    - curl https://raw.githubusercontent.com/mcflugen/hydrotrend/add-bmi-metadata/data/input/HYDRO.IN > ./input/HYDRO.IN
    - curl https://raw.githubusercontent.com/mcflugen/hydrotrend/add-bmi-metadata/data/input/HYDRO0.HYPS > ./input/HYDRO0.HYPS
    - hydrotrend --prefix=HYDRO --in-dir=./input --out-dir=./output

build:
  string: {{ build_string }}

about:
  home: http://csdms.colorado.edu/wiki/Model:HydroTrend
  license: MIT
  summary: Climate driven hydrological transport model
  description: |
    HydroTrend v.3.0 is a climate-driven hydrological water balance
    and transport model that simulates water discharge and sediment
    load at a river outlet.
  doc_url: http://csdms.colorado.edu/wiki/Model:HydroTrend
  dev_url: http://github.com/mcflugen/hydrotrend
