language: generic
os:
- linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda2-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: vYS98/Rl+f6cJK/LtZtiGdV3nw1EO19MFkwMOuVEOsPDhKdhb5Og7EZWwWMnQLQpM3vJiauxJm5cVwV4d3RyEi5UzS/mDZy+uhGlGpkgNwUjAv43U6pn+yURTKLvNGEtqzvjr15CfsAReXze/NK9ODz2QHkkjCuzSW4ji5tyGz2nQgDDI0jXx3Fx/Y8Aho6cCyn34L75vYpz8CMEoyIkOSNfcI43wTBLtERKgXletQmFRX3HvfT8ipXkAlo2n7TkHlYnL2js2q4JX8gU6lj4JMhEEZKv3NiVmKVrkm1aSxRWVAjhO+l3rhNpayaJ29f1PbElj4q+XhmqBnO6mLx+NFA7CfbE/sof5zgfSXXHYiqhSirgg4S7EWJCw0NpgcfrvukEyGnzz+f0yGlirbSYA/1JQ4dbxbOqITycyNDeLPGwKo/zDuNyxjn+V9yNa8T3/4niVYxF5wx3npyiSyvJEZ/SvFjBPY0OrlQAGEMv+wfXJRpDrydNdgksSB328b5QrCEpnVdfcdZUcgFqmGB+yzhyr4CWxi6eROQjTgKiuNXkVhmboWOrUHIYlIF5AULhrfzIRzXBrX7psmGCpcBAvMau0gNhoSDhTFi6kkbZSpFAB7TwfzMYCoHMx7gu3oA8tZa630zHVjcHpMJuNyoE8xEyG7Dq4wnB4c1pXbl3oLQ=
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c csdms-stack -c conda-forge
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack
  --token=-
