language: generic
os:
- linux
- osx
env:
  global:
  - THIS_PACKAGE=hydrotrend
  - TRAVIS_PYTHON_VERSION="2.7"
  - NUMPY_VERSION="1.9"
sudo: false
install:
- bash ci/travis/install_python.sh $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
script:
- conda build recipe -c conda-forge -c csdms/channel/dev -c csdms
after_success:
- bash ci/travis/deploy_to_anaconda.sh $THIS_PACKAGE
