environment:
  global:
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\ci\\appveyor\\run_with_env.cmd"
    PYTHONIOENCODING: "UTF-8"
    CONDA_NPY: 1.10
  matrix:
    - PYTHON: "C:\\Python27"
      DISTUTILS_USE_SDK: "1"
      PYTHON_VERSION: "2.7"

artifacts:
  - path: 'dist\*'

platform:
  - x64
  - x86

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %HOME% %PLATFORM%"
  - "ECHO %APPVEYOR_REPO_BRANCH%"

install:
  - powershell ci/appveyor/install.ps1
  - IF "%PLATFORM%"=="x64" (SET SUFFIX="_64") ELSE (SET SUFFIX="_32")
  - "set PATH=%PYTHON%%SUFFIX%;%PYTHON%%SUFFIX%/Scripts;%PYTHON%%SUFFIX%/Library/bin;%PATH%"
  - cmd: conda config --add channels conda-forge
  - cmd: conda config --add channels csdms/channel/dev
  - cmd: conda config --set show_channel_urls true
  - cmd: conda update --yes --quiet conda
  - cmd: conda install --yes --quiet jinja2 conda-build anaconda-client
  - cmd: conda install --yes --quiet conda-build=1
  - cmd: conda list
  - cmd: conda info
  - cmd: conda config --get

test_script:
  - "%WITH_COMPILER% conda build -q recipe"

build: false
