environment:
  global:
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\.ci\\appveyor\\run_with_env.cmd"
    PYTHONIOENCODING: "UTF-8"
    CONDA_NPY: 1.10
  matrix:
    - PYTHON: "C:\\Python27"
      DISTUTILS_USE_SDK: "1"
      PYTHON_VERSION: "2.7"


artifacts:
  # Store built conda packages as artifacts
  - path: 'conda_packages\*.bz2'

platform:
  - x64
  - x86

install:
  - cmd: set "OLDPATH=%PATH%"
  - cmd: set "PATH=%CONDA_INSTALL_LOCN%\\Scripts;%CONDA_INSTALL_LOCN%\\Library\\bin;%PATH%"
  - cmd: conda update --yes --quiet conda
  - cmd: set "PATH=%OLDPATH%"
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda config --add channels conda-forge
  - cmd: conda config --add channels csdms/channel/dev
  - cmd: conda config --set show_channel_urls true
  - cmd: conda update --yes --quiet conda
  - cmd: conda install --yes --quiet jinja2 conda-build anaconda-client
  - cmd: conda install --yes --quiet conda-build=1
  - cmd: conda info
  - cmd: conda config --get

test_script:
  - "%WITH_COMPILER% conda build -q recipe"

build: off
